### ISSUE TITLE
climeta & winrt-rust

### ISSUE THREAD

**Issue by Boddlnagg** [microsoft/winmd-rs#13]
I wonder if you've seen the https://github.com/Boddlnagg/climeta project, and (as the larger context), the https://github.com/contextfree/winrt-rust project?

Seems like the goal is basically the same as what you're doing here. I'm currently the maintainer of both projects, but I don't really have much time to work on it. I'm very happy that you (and Microsoft) are looking into this space officially now.
I just wonder if there's something you can reuse from the existing projects so you don't have to reinvent the wheel ;-)

**Comment by kennykerr** [comment]
Absolutely! I did come across the contextfree project. I reached out to Max but couldn't find your email address. I'm sure there is much we can learn. Feel free to email me - [kenny.kerr@microsoft.com](mailto:kenny.kerr@microsoft.com) - would love to chat about our plans and aspirations.
